name: CI

on: [push]

jobs:
  build:
    name: Linting

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: make install
    - name: Run linting
      run: |
        make lint
