name: CI

on: [push]

jobs:
  build:
    name: Linting

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '13.x'
      - name: npm install
        run: make install
      - name: Run linting
        run: make lint
